dm1103: fix incorrect button text when a proposal has already been submitted
bcgov/digital_marketplace pull request #339
Opened 2022-12-15 19:51 UTC by sutherlanda

This PR closes issue: [DM-1103]

Proposed changes:
- The http crud api was intending to return a `ResponseValidation` wrapping a `CWUOpportunityProposal`, but it was actually just returning the unwrapped proposal object. This was the root cause of the failed `isValid` check when determining whether an existing proposal was present or not.
- The fix was to ensure the http crud api wrapped the proposal object in a `ResponseValidation`. Validation was already being performed by the `readMany` crud action

2022-12-15 20:22 UTC, IanFonzie requested changes
Looks good, I think we need these changes in SWU as well

2022-12-15 20:38 UTC, sutherlanda commented
> Looks good, I think we need these changes in SWU as well

Right, thanks. Added the equivalent fix for SWU as well.

2022-12-15 22:46 UTC, IanFonzie approved these changes

2022-12-16 17:43 UTC, dhruvio requested changes

2022-12-16 17:43 UTC, dhruvio commented on src/front-end/typescript/lib/pages/opportunity/code-with-us/view.tsx
> +              (response) => valid(response)
Checking the type signature for `readExistingProposalForOpportunity`:

https://github.com/bcgov/digital_marketplace/blob/aa017d5d19ba37d3ded0f93827fdf75c88e41cb2/src/front-end/typescript/lib/http/api/proposal/code-with-us.ts#L43-L54

It looks like it handles the validation there already, and passes a `CWUProposalSlim | undefined` to the `handleResponse` function.

In this case, I think the fix is to change the `InnerMsg` type in this file on L59 from:

```ts
api.ResponseValidation<CWUProposalSlim, string[]> | null
```

to:

```ts
CWUProposalSlim | null
```

And update the rest of the module accordingly.

2022-12-16 17:43 UTC, dhruvio commented on src/front-end/typescript/lib/pages/opportunity/code-with-us/view.tsx
> +              (response) => valid(response)
Ah, the use of `unknown` in the HTTP client libraries is really letting a lot of stuff slip through the cracks :( My apologies

2022-12-16 20:42 UTC, dhruvio approved these changes

2022-12-16 20:43 UTC, merged