Dm1083 unsubscribe footer
bcgov/digital_marketplace pull request #348
Opened 2023-01-12 00:43 UTC by IanFonzie

This PR closes issue: [DM-1083]

Includes tests? [N]
Updated docs? [N]

Proposed changes:
- Redirect to viewer user profile when userId route param is "me"
- Add unsubcribe URL to email layout
- Add modal to unsubscribe users when unsubscribe query param is present on the notifications tab

2023-01-12 18:39 UTC, bdolor requested changes
looks good! just a couple minor tweaks

2023-01-12 22:35 UTC, IanFonzie commented on src/front-end/typescript/lib/pages/user/profile/tab/notifications.tsx
> +    switch (state.showModal.tag) {
I went ahead and removed it but the change is isolated; @dhruvio any opinions on this?

2023-01-13 00:22 UTC, dhruvio commented on src/front-end/typescript/lib/pages/user/profile/tab/notifications.tsx
> +    switch (state.showModal.tag) {
I think either approach to implementation is fine as long as the code compiles successfully without type errors.

2023-01-13 18:39 UTC, bdolor approved these changes

2023-01-13 19:26 UTC, merged